changelog:
  exclude:
    labels:
      - invalid
  categories:
    - title: New Features 🎉
      labels:
        - nonexistent-label
        - enhancement
    - title: Bugfixes 🛠
      labels:
        - bug
    - title: Docmentation 📖
      labels:
        - documentation
    - title: Other Changes 🤔
      labels:
        - "*"
